### ISSUE TITLE
Review bounds

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-print#4]
https://github.com/CartoDB/carto-print/blob/c78d0539351901599dc89ee3a010f6b7639b76af/carto/print.py#L74-L78

Are these correct? I had to change those lines to this:

```python
          max_y = self.bounds['north']
          min_y = self.bounds['south']
          max_x = self.bounds['west']
          min_x = self.bounds['east']
```

**Comment by alrocar** [comment]
Dups https://github.com/CartoDB/carto-print/issues/3
